# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Some Notes
email: barrywuh@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This site is set up for sharing some interesting notes. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  barrywuh

# Build settings
markdown: kramdown
math_engine: mathjax
# theme
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
